#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8001/eureka/
#
#    register-with-eureka: false
#    fetch-registry: false
server:
  port: 9970

spring:
  application:
    name: timely-rain-server
  data:
    mongodb:
#      your mongodb
      uri: mongodb://timely-rain:123456@localhost:27017/timelyrain
